In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.layers import LSTM, Dense
from keras.models import Sequential
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import sys, os
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.layers.convolutional import Conv1D
from sklearn.utils import shuffle
from tensorflow import keras
from tensorflow.keras.layers import Bidirectional
import tensorflow as tf
from tensorflow.keras.layers import Input, Dropout, Dense, LSTM, TimeDistributed, RepeatVector
from tensorflow.keras.layers import TimeDistributed
from keras.models import Model
from keras import regularizers
from keras.layers  import  LSTM
from keras.optimizers import Adam
from keras import regularizers
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.layers import Dense, LSTM, Dropout, RepeatVector
from keras.models import Model
import tensorflow as tf
import math, sys, time
import datetime
from tensorflow.keras.callbacks import ModelCheckpoint

from keras.layers import Input, Dropout, Dense, LSTM, TimeDistributed, RepeatVector
from keras.models import Model
from keras import regularizers
# Multiple Inputs
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout, RepeatVector, TimeDistributed
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import GRU
from tensorflow.keras.layers import MaxPooling1D
from tensorflow.keras.layers import RepeatVector
from tensorflow.keras.layers import TimeDistributed
#from tensorflow.keras.layers.convolutional import Conv2D
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import concatenate
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.models import load_model
import math, sys, time
# Use scikit-learn to grid search the batch size and epochs
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import GRU, TimeDistributed, LSTM
from keras.callbacks import ModelCheckpoint
from keras.layers import Dense, Flatten, Dropout, Input
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

from pandas._testing import assert_frame_equal
from pandas.testing import assert_index_equal

#assert sys.version_info >= (3, 5)
#assert sklearn.__version__ >= "0.20"

In [2]:
from EEGP import EEGPreprocessor
from neuralstart_filter import EEGFilter
import pandas as pd
import numpy as np
from sklearn.utils import resample
from scipy.signal import butter, filtfilt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.sequence import pad_sequences
import pywt
from encoder_neuralstart import LabelEncoderModel
from scaler_neuralstar import ScalerHandler
from Neuralstart_process2 import EEGDataPreprocessor

In [3]:
df = pd.read_csv("/Users/charleshajjar/Documents/DataAnalyse/data/CaptureSamples/charles_5m-2s-2.csv")
df = df.iloc[:500]

In [4]:
# Créer une instance de la classe EEGFilter
eeg_filter = EEGFilter(lowcut=4.0, highcut=1.0, order=4, fs=250.0)
# Appliquer les filtres au dataframe
df = eeg_filter.filter_dataframe(df)
preprocessor = EEGPreprocessor(df)
filtered_df = preprocessor.apply_butter_filter()
results_df = preprocessor.detect_threshold_changes()
filtered_df = preprocessor.convert_timestamp()
filtered_df = preprocessor.label_thinking_periods(results_df)
transformed_data_df = preprocessor.transform_data(filtered_df)
calculated_p_value_df = preprocessor.calculate_p_value(filtered_df)
p_value_df = filtered_df.assign(p_value=calculated_p_value_df['p_value'])
fdr = preprocessor.fdr_correction(p_value_df)

/Users/charleshajjar/Documents/DataAnalyse/EEGP.py:102: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({"EEG Column": column, "Start Time": start_time, "End Time": end_time},
/Users/charleshajjar/Documents/DataAnalyse/EEGP.py:102: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({"EEG Column": column, "Start Time": start_time, "End Time": end_time},
/Users/charleshajjar/Documents/DataAnalyse/EEGP.py:102: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results_df = results_df.append({"EEG Column": column, "Start Time": start_time, "End Time": end_time},
/Users/charleshajjar/Documents/DataAnalyse/EEGP.py:102: FutureWarning: The frame.append method is deprecated and will 

/Users/charleshajjar/NeuralStar/lib/python3.9/site-packages/scipy/stats/_morestats.py:3414: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/charleshajjar/NeuralStar/lib/python3.9/site-packages/scipy/stats/_morestats.py:3414: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/charleshajjar/NeuralStar/lib/python3.9/site-packages/scipy/stats/_morestats.py:3414: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/charleshajjar/NeuralStar/lib/python3.9/site-packages/scipy/stats/_morestats.py:3414: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal

In [5]:
label_encoder_model = LabelEncoderModel("Label")
label_encoder_model.fit(fdr)
# Enregistrement du modèle
label_encoder_model.save("Label_process2.joblib")
label_encoder_model.load("Label_process2.joblib")
# Transformation des données
fdr = label_encoder_model.transform(fdr)

In [6]:
direction_encoder_model = LabelEncoderModel("Direction")
direction_encoder_model.fit(fdr)
# Enregistrement du modèle
direction_encoder_model.save("direction_process2.joblib")
direction_encoder_model.load("direction_process2.joblib")
fdr = direction_encoder_model.transform(fdr)
scaler_handler = ScalerHandler('./scaler_process2.joblib')
# Chargement du modèle de normalisation à partir du chemin
fdr = scaler_handler.standardize_data(fdr)

In [7]:
X, y = preprocessor.get_sequences_labels_omega(fdr, 10)

In [8]:
unique_vals, counts = np.unique(y, return_counts=True)

print(unique_vals)
print(counts)

[0. 5.]
[1 9]


In [9]:
########TESTT

In [10]:
df2 = pd.read_csv("/Users/charleshajjar/Documents/DataAnalyse/data_modif_5m_2s.csv")

In [11]:
# Créer une instance de la classe EEGDataPreprocessor
#preprocessor = EEGDataPreprocessor(df2)
# Appeler la méthode preprocess_data pour preprocessor les données
#fdr2 = preprocessor.preprocess_data()

In [12]:
preprocessor = EEGPreprocessor(df2)
X_, y_ = preprocessor.get_sequences_labels_omega(df2, 10)

In [13]:
unique_valss, countss = np.unique(y_, return_counts=True)

print(unique_valss)
print(countss)

[0. 1. 2. 3. 4. 5.]
[ 1044  1069   859   690   389 53124]


In [14]:
# Séparation en données d'entraînement et de validation
X_train, X_val, y_train, y_val = train_test_split(X_, y_, test_size=0.2, random_state=42)

In [35]:
X_train.shape

(45740, 10, 18)

In [15]:
sys.path.append('/Users/charleshajjar/Documents/DataAnalyse/neuralstart_model')
from Gate_activation import GatedActivationUnit
from NeuralNet import WaveNet_EEGModel

In [45]:
from sklearn.datasets import make_classification
from sklearn.utils import compute_class_weight
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
model = Sequential()
model.add(Conv1D(32, (3,), activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(MaxPooling1D(2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(6, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
classes = np.unique(y_train)
class_weights = compute_class_weight(class_weight = "balanced", classes= classes, y= y_train)
class_weights = {i: w for i, w in enumerate(class_weights)}

In [46]:
model.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_val, y_val), shuffle=True, class_weight=class_weights)

Epoch 1/10
458/458 [==============================] - 2s 3ms/step - loss: 0.8023 - accuracy: 0.9166 - val_loss: 0.1180 - val_accuracy: 0.9690
Epoch 2/10
458/458 [==============================] - 1s 2ms/step - loss: 0.1902 - accuracy: 0.9807 - val_loss: 0.0327 - val_accuracy: 0.9879
Epoch 3/10
458/458 [==============================] - 1s 2ms/step - loss: 0.0763 - accuracy: 0.9915 - val_loss: 0.0208 - val_accuracy: 0.9922
Epoch 4/10
458/458 [==============================] - 1s 2ms/step - loss: 0.0470 - accuracy: 0.9974 - val_loss: 0.0103 - val_accuracy: 0.9982
Epoch 5/10
458/458 [==============================] - 1s 2ms/step - loss: 0.0255 - accuracy: 0.9990 - val_loss: 0.0062 - val_accuracy: 0.9988
Epoch 6/10
458/458 [==============================] - 1s 2ms/step - loss: 0.0316 - accuracy: 0.9992 - val_loss: 0.0053 - val_accuracy: 0.9990
Epoch 7/10
458/458 [==============================] - 1s 2ms/step - loss: 0.0320 - accuracy: 0.9993 - val_loss: 0.0054 - val_accuracy: 0.9987
Epoch 

In [47]:
# Évaluer la performance du modèle sur les données de test
test_loss, test_acc = model.evaluate(X_val, y_val, verbose=2)
print('\nTest accuracy:', test_acc)

358/358 - 0s - loss: 0.0024 - accuracy: 0.9991 - 325ms/epoch - 908us/step

Test accuracy: 0.9991254806518555


In [48]:
# Évaluer la performance du modèle sur les données de test
test_loss, test_acc = model.evaluate(X, y, verbose=2)
print('\nTest accuracy:', test_acc)
print('\nTest loss:', test_loss)

1/1 - 0s - loss: 0.0314 - accuracy: 1.0000 - 20ms/epoch - 20ms/step

Test accuracy: 1.0

Test loss: 0.03141096606850624


In [50]:
val_predictions = model.predict(X_val)
val_classes = val_predictions.argmax(axis=1)

358/358 [==============================] - 1s 843us/step


In [51]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
# Créer la matrice de confusion
cm = confusion_matrix(y_val, val_classes)
print('Matrice de confusion :')
print(cm)

# Calculer les métriques de performance
acc = accuracy_score(y_val, val_classes)
prec = precision_score(y_val, val_classes,average='micro')
rec = recall_score(y_val, val_classes,average='micro')
f1 = f1_score(y_val, val_classes,average='micro')

print('Accuracy :', acc)
print('Precision :', prec)
print('Recall :', rec)
print('F1 Score :', f1)

Matrice de confusion :
[[  218     0     0     0     0     1]
 [    0   193     0     0     0     1]
 [    0     0   149     4     0     0]
 [    0     0     0   140     1     0]
 [    0     0     0     2    68     0]
 [    0     0     0     0     1 10657]]
Accuracy : 0.9991254919108001
Precision : 0.9991254919108001
Recall : 0.9991254919108001
F1 Score : 0.9991254919108001


In [52]:
val_predictions = model.predict(X)
val_classes = val_predictions.argmax(axis=1)

1/1 [==============================] - 0s 21ms/step


In [53]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
# Créer la matrice de confusion
cm = confusion_matrix(y, val_classes)
print('Matrice de confusion :')
print(cm)

# Calculer les métriques de performance
acc = accuracy_score(y, val_classes)
prec = precision_score(y, val_classes,average='micro')
rec = recall_score(y, val_classes,average='micro')
f1 = f1_score(y, val_classes,average='micro')

print('Accuracy :', acc)
print('Precision :', prec)
print('Recall :', rec)
print('F1 Score :', f1)

Matrice de confusion :
[[1 0]
 [0 9]]
Accuracy : 1.0
Precision : 1.0
Recall : 1.0
F1 Score : 1.0
